routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();
Route::group(['middleware' =>['auth']], function()
{
    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
    Route::resource('/task','TaskController')->except('show');
    Route::get('/task-inProgress','TaskController@inProgress')->name('task.inProgress');
    Route::get('/task-done','TaskController@Done')->name('task.done');

    Route::put('/task/moveToInProgress/{task}','TaskController@moveToInProgress')->name('task.moveToInProgress');
    Route::put('/task/moveToDone/{task}','TaskController@moveToDone')->name('task.moveToDone');
    Route::put('/task/moveToToDo/{task}','TaskController@moveToToDo')->name('task.moveToToDo');

    Route::get('/archive','TaskController@Archive')->name('archive');

    Route::get('/settings','UserSettingsController@index')->name('settings');
    Route::put('/profile-update','UserSettingsController@updateProfile')->name('profile.update');
    Route::put('/password-update','UserSettingsController@updatePassword')->name('password.update');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class TaskController extends Controller
{

    public function index()
    {
        $tasksTodo=Auth::user()->tasks()->where('category_id' ,'=', 1)->get();

        return view('tasks.todo',compact('tasksTodo'));
    }

    public function create()
    {
       return view('tasks.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $slug=Str::slug($request->name);

        $task=new Task();

        $task->name=$request->name;
        $task->label=$request->label;
        $task->deadline=Carbon::parse($request->deadline);

        $task->user_id=Auth()->id();
        $task->category_id=1;//meaning to do
        $task->slug=$slug;

        $task->save();
        Toastr::success('Post Created', 'Success');

        return redirect()->route('task.index');

    }

    public function edit(Task $task)
    {
        if($task->user_id  !== Auth::id())
        {
            Toastr::error('You have no autorization','error');
            return redirect()->back();
        }
        return view('tasks.edit',compact('task'));
    }

    public function update(Request $request, Task $task)
    {
        if($task->user_id  !== Auth::id())
        {
            Toastr::error('You have no autorization','error');
            return redirect()->back();
        }

        $this->validate($request, [
            'name' => 'required',
        ]);

        $slug=Str::slug($request->name);

        $task->name=$request->name;
        $task->label=$request->label;
        $task->deadline=Carbon::parse($request->deadline);

        $task->user_id=Auth()->id();
        $task->category_id=1;//meaning to do
        $task->slug=$slug;

        $task->save();
        Toastr::success('Task Updated Created', 'Success');

        return redirect()->back();
    }

    public function destroy(Task $task)
    {
        if($task->user_id  !== Auth::id())
        {
            Toastr::error('You have no autorization','error');
            return redirect()->back();
        }

        $task->delete();
        Toastr::success('Post Deleted', 'Success');

        return redirect()->back();
    }

    public function moveToInProgress(Task $task)
    {
        if($task->user_id  !== Auth::id())
        {
            Toastr::error('You have no autorization','error');
            return redirect()->back();
        }
        $task->category_id=2;

        $task->save();

        Toastr::success('Task moved to In Progress', 'Success');
        return redirect()->back();
    }

    public function moveToDone(Task $task)
    {
        if($task->user_id  !== Auth::id())
        {
            Toastr::error('You have no autorization','error');
            return redirect()->back();
        }

        $task->category_id=3;

        $task->save();

        Toastr::success('Task moved to In Progress', 'Success');
        return redirect()->back();
    }

    public function moveToToDo(Task $task)
    {
        if($task->user_id  !== Auth::id())
        {
            Toastr::error('You have no autorization','error');
            return redirect()->back();
        }

        $task->category_id=1;

        $task->save();

        Toastr::success('Task moved to In Progress', 'Success');
        return redirect()->back();
    }

    public function inProgress(Task $task)
    {
        $tasksInProgress=Auth::user()->tasks()->where('category_id' ,'=', 2)->get();

        return view('tasks.in-progress',compact('tasksInProgress'));
    }

    public function Done(Task $task)
    {
        /*$tasksDone=Task::where('category_id' ,'=', 3)->get();*/
        $tasksDone=Auth::user()->tasks()->where('category_id' ,'=', 3)->get();

        return view('tasks.done',compact('tasksDone'));
    }

    public function Archive()
    {
        $archives=Auth::user()->archiveTasks()->get();

        return view('archive.index',compact('archives'));
    }


}

resources/views/tasks/create.blade.php
@extends('layouts.backend.app')

@section('title',"Task")

@push('css')

@endpush

@section('content')


    <div class="container-fluid">

        <!-- Vertical Layout -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Add New Task
                        </h2>
                    </div>
                    <div class="body">
                        <form action="{{route('task.store')}}" method="Post" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="name" class="form-control" name="name" placeholder="">
                                    <label class="form-label">Task Name</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="label" class="form-control" name="label" placeholder="">
                                    <label class="form-label"> Task Label</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <h2 class="card-inside-title">Task Deadline</h2>
                                <div class="form-line">
                                    <input type="datetime-local" id="label" class="form-control" name="deadline" placeholder="">
                                </div>
                            </div>

                            <a class="btn btn-danger m-t-15 waves-effect"
                               href="{{route('task.index')}}">
                                Back
                            </a>

                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Vertical Layout -->
    <!-- Vertical Layout | With Floating Label -->
@endsection
@push('js')

@endpush

resources/views/tasks/done.blade.php
@extends('layouts.backend.app')

@section('title',"Task")

@push('css')
    <!-- Animation Css -->

    <link href="{{asset('assets/backend/plugins/animate-css/animate.css')}}"
          rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <h1>Done Tasks</h1>
        </div>
        <!-- Basic Example -->
        <div class="row clearfix">

            @forelse($tasksDone as $task)
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="card">
                        <div class="header bg-green">
                            <h2>
                                {{$task->name}}
                                <small>
                                    Due Date: {{\Carbon\Carbon::parse($task->deadline)->diffForHumans()}}
                                </small>
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="{{route('task.edit',$task->id)}}">
                                                Edit Task
                                            </a>
                                        </li>

                                        <li>
                                            <form action="{{ route('task.moveToToDo',$task->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <button type="submit" style="width: 160px "
                                                        class="btn btn-default waves-effect">Move to ToDo
                                                </button>
                                            </form>
                                        </li>

                                        <li>
                                            <form action="{{ route('task.moveToInProgress',$task->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <button style="width: 160px " type="submit"
                                                        class="btn btn-success waves-effect">Move to In Progress
                                                </button>
                                            </form>
                                        </li>

                                        <li class="btn btn-danger waves-effect" onclick="deleteCategory({{$task->id}})">
                                            Delete Task
                                            <form id="delete-form-{{$task->id}}"
                                                  action="{{route('task.destroy',$task->id)}}" method="Post"
                                                  style="display: none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            {{$task->label}}
                        </div>
                    </div>
                </div>
            @empty
                <div>
                    <h3>No tasks in Done</h3>
                </div>
            @endforelse
        </div>
    </div>

@endsection
@push('js')
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.5.1/dist/sweetalert2.all.min.js"></script>
    {{--Za deletirajne na tag--}}
    <script>
        function deleteCategory(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-' + id).submit();
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your task is save',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/tasks/edit.blade.php
@extends('layouts.backend.app')

@section('title',"Task")

@push('css')

@endpush

@section('content')


<div class="container-fluid">

    <!-- Vertical Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Edit Task
                    </h2>
                </div>
                <div class="body">
                    <form action="{{route('task.update',$task->id)}}" method="Post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" class="form-control" name="name" value="{{$task->name}}" placeholder="">
                                <label class="form-label">Task Name</label>
                            </div>
                        </div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="label" class="form-control" name="label" value="{{$task->label}}" placeholder="">
                                <label class="form-label"> Task Label</label>
                            </div>
                        </div>

                        <div class="form-group form-float">
                            <h2 class="card-inside-title">Task Deadline</h2>
                            <div class="form-line">
                                <input type="datetime-local" id="deadline" class="form-control" name="deadline" value="{{old('time')?? date('Y-m-d\TH:i', strtotime($task->deadline)) }}" placeholder="">
                            </div>
                        </div>

                        <a class="btn btn-danger m-t-15 waves-effect"
                           href="{{route('task.index')}}">
                            Back
                        </a>

                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- #END# Vertical Layout -->
    <!-- Vertical Layout | With Floating Label -->
@endsection
@push('js')

@endpush

resources/views/tasks/in-progress.blade.php
@extends('layouts.backend.app')

@section('title',"Task")

@push('css')
    <!-- Animation Css -->

    <link href="{{asset('assets/backend/plugins/animate-css/animate.css')}}"
          rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <h1>In Progress Tasks</h1>
        </div>
        <!-- Basic Example -->
        <div class="row clearfix">

            @forelse($tasksInProgress as $task)
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="card">
                        <div class="header bg-orange">
                            <h2>
                                {{$task->name}}
                                <small>
                                    Due Date: {{\Carbon\Carbon::parse($task->deadline)->diffForHumans()}}
                                </small>
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="{{route('task.edit',$task->id)}}">
                                                Edit Task
                                            </a>
                                        </li>

                                        <li>
                                            <form action="{{ route('task.moveToToDo',$task->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <button type="submit" style="width: 160px "
                                                        class="btn btn-default waves-effect">Move to ToDo
                                                </button>
                                            </form>
                                        </li>

                                        <li>
                                            <form action="{{ route('task.moveToDone',$task->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <button style="width: 160px " type="submit"
                                                        class="btn btn-success waves-effect">Move to Done
                                                </button>
                                            </form>
                                        </li>

                                        <li class="btn btn-danger waves-effect" onclick="deleteCategory({{$task->id}})">
                                            Delete Task
                                            <form id="delete-form-{{$task->id}}"
                                                  action="{{route('task.destroy',$task->id)}}" method="Post"
                                                  style="display: none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            {{$task->label}}
                        </div>
                    </div>
                </div>
            @empty
                <div>
                    <h3>No tasks in Progress</h3>
                </div>
            @endforelse
        </div>
    </div>

@endsection
@push('js')
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.5.1/dist/sweetalert2.all.min.js"></script>
    {{--Za deletirajne na tag--}}
    <script>
        function deleteCategory(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-' + id).submit();
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your task is save',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/tasks/todo.blade.php
@extends('layouts.backend.app')

@section('title',"Task")

@push('css')
    <!-- Animation Css -->

    <link href="{{asset('assets/backend/plugins/animate-css/animate.css')}}"
          rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <h1>Todo Tasks</h1>
        </div>
        <!-- Basic Example -->
        <div class="row clearfix">

            @forelse($tasksTodo as $task)
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>
                                {{$task->name}}
                                <small>
                                    Due Date: {{\Carbon\Carbon::parse($task->deadline)->diffForHumans()}}
                                </small>
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="{{route('task.edit',$task->id)}}">
                                                Edit Task
                                            </a>
                                        </li>

                                        <li>
                                            <form action="{{ route('task.moveToInProgress',$task->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <button type="submit" style="width: 160px "
                                                        class="btn btn-default waves-effect">Move to In
                                                    Progress
                                                </button>
                                            </form>
                                        </li>

                                        <li>
                                            <form action="{{ route('task.moveToDone',$task->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <button style="width: 160px " type="submit"
                                                        class="btn btn-success waves-effect">Move to Done
                                                </button>
                                            </form>
                                        </li>

                                        <li class="btn btn-danger waves-effect" onclick="deleteCategory({{$task->id}})">
                                            Delete Task
                                            <form id="delete-form-{{$task->id}}"
                                                  action="{{route('task.destroy',$task->id)}}" method="Post"
                                                  style="display: none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            {{$task->label}}
                        </div>
                    </div>
                </div>
            @empty
                <div>
                    <h3>No tasks in Todo. You can add tasks
                        <button><a href="{{route('task.create')}}">here</a></button>
                    </h3>
                </div>
            @endforelse
        </div>
    </div>

@endsection
@push('js')
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.5.1/dist/sweetalert2.all.min.js"></script>
    {{--Za deletirajne na tag--}}
    <script>
        function deleteCategory(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-' + id).submit();
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your task is save',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush